### ISSUE TITLE
There have some errors in your code

### ISSUE THREAD

**Issue by MiniCat123** [coczero/RPG-Maker-WPF#1]
Error:
RPG_Maker_WPF.ViewModels.ProjectViewModel.CurrentProject.get null

File
Database.cs line 37:

Code
string path = ProjectViewModel.CurrentProject.Path + "\\Data\\ActorData.rpgwpfd";

The file "ActorData.rpgwpfd" is not exist!

Can you supply the file?

**Comment by SHOEGAZEssb** [comment]
Sorry this project is out of development and does not offer any functionality anymore
